In [1]:
10**6

1000000

introduction to numpy:
numpy is powerful library that provides suppoet for arrays,matrices,nd mathematical functions,making it a core tool in scientific computing and data analysis.
numpy class:


Difference between numpy and list in code:

In [3]:
python_list =[1,3,5,7,9]
python_list_with_2 = [x+2 for x in python_list]
print("python list with 2 added:", python_list_with_2)

import numpy as np

numpy_array = np.array([1,3,5,7,9])
numpy_array_with_2 = numpy_array + 2
print("numpy array with 2 added:", numpy_array_with_2)

python list with 2 added: [3, 5, 7, 9, 11]
numpy array with 2 added: [ 3  5  7  9 11]


In [4]:
for x in python_list:
    x+2
print("python list with 2 added:", python_list_with_2)    

python list with 2 added: [3, 5, 7, 9, 11]


In [5]:
aa = list(map(lambda x:x+2,python_list))
aa

[3, 5, 7, 9, 11]

perfomance

In [7]:
import time
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))



start_time = time.time()
python_list_sum = [x + 2 for x in python_list]
end_time = time.time()
print(f"Time taken for python list addition:{end_time - start_time} seconds")

start_time = time.time()
numpy_array_sum = numpy_array +2
end_time = time.time()
print(f"Time taken for numpy array addition:{end_time - start_time} seconds")



Time taken for python list addition:0.09196257591247559 seconds
Time taken for numpy array addition:0.0019826889038085938 seconds


memory

In [9]:
import sys

In [10]:
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))

size_python_list = sys.getsizeof(python_list)
size_numpy_array = numpy_array.nbytes

print(f"size of python list:{size_python_list} bytes")
print(f"size of numpy array:{size_numpy_array} bytes")



size of python list:8000056 bytes
size of numpy array:8000000 bytes


numpy vs linspace

In [11]:
arr1 = np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [12]:
arr2 =np.linspace(0,10,num=6)
arr2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [13]:
t = np.linspace(0,20,10, endpoint=False, dtype='int')
t

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

types of numpy array - numpy create 1D Array

In [14]:
arr3 = np.array([5,8,12])

print(arr3)

[ 5  8 12]


create 1d numpy array using arrange() function

In [15]:
arr4 = np.arange(5,14,2)

print(arr4)

[ 5  7  9 11 13]


numpy 2D array

In [17]:
arr5 = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr6 = np.zeros((3,4), dtype=int)

print(arr6)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
shape = (3,4)

arr7 =np.ones(shape, dtype='int')

print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
arr8 = np.empty((3,4), dtype =int)

print (arr8)

[[25895968444448860 23925768161198179 32370111954616435 30681201964548188]
 [19140693560524905 30681274979123311 32370120545140837 32651616996819036]
 [25896170311057512 31525665550696526 12948029323346041      386547056682]]


numpy 3d array

In [21]:
nested_list = [[[1,2,3,4], [5,6,7,8],[9,10,11,12]],
[[13,14,15,16], [17,18,19,20], [21,22,23,24]]]

arr9 = np.array (nested_list)

print(arr9)               

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [22]:
shape = (2, 3, 4)

arr11 = np.zeros(shape)

print(arr11)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [23]:
shape = (2,3,4)
arr12 = np.empty(shape)

print(arr12)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


numpy.random module:

numpy.random.rand:

In [24]:
random_numbers = np.random.rand(2,3)
random_numbers

array([[0.88286798, 0.28330859, 0.31577397],
       [0.43423214, 0.23595735, 0.32270836]])

numpy.random.randn:

In [25]:
random_numbers = np.random.randn(2,3)
random_numbers

array([[-0.59223902,  0.75511733,  1.06242694],
       [ 0.12297079,  1.14618135, -0.39687022]])

numpy.random.randint:

In [26]:
random_integers = np.random.randint(-10,10, size = (2,3))
random_integers

array([[ 8,  5, -9],
       [ 3, -2,  3]], dtype=int32)

creating numpy array

In [1]:
import numpy as np
ac = np.array([2,4,56,422,32,1])
ac

array([  2,   4,  56, 422,  32,   1])

In [3]:
az = np.array([2.01,2.02,2.03])
az

array([2.01, 2.02, 2.03])

In [4]:
ay = [1,2,3,4,5,6]
for i in ay:
    print(f"{i} = {type(i)}")

1 = <class 'int'>
2 = <class 'int'>
3 = <class 'int'>
4 = <class 'int'>
5 = <class 'int'>
6 = <class 'int'>


In [5]:
#to find the type
type(ac)

numpy.ndarray

In [6]:
np.arange(2,10, dtype = float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
i =np.identity(4)  #identity matrix is that diagonal items will be ones and everything will be zeros 
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
diagonal_mat = np.diag([1,2])
diagonal_mat

array([[1, 0],
       [0, 2]])

In [14]:
specific = np.full((3,3),7)
specific

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [10]:
#copyying the bumpy into another variable
x = np.array([1,2,3])
y = x
z = np.copy(x)
x,y,z

(array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3]))

In [11]:
np.linspace(2.0, 3.0, num =5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [12]:
np.linspace(2.0, 3.0, num =5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

changing the type of the data type

In [15]:
ad = np.array([11,23,44], dtype = float)
ad

array([11., 23., 44.])

In [16]:
af = np.array([11,23,44],dtype= complex )
af

array([11.+0.j, 23.+0.j, 44.+0.j])

In [17]:
af.astype(int)

C:\Users\admin\AppData\Local\Temp\ipykernel_4636\4115513463.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  af.astype(int)


array([11, 23, 44])

In [18]:
#numpy.arange creates arrays with regularly incrementing values. check the documentation for complete information and examples.
np.array([127, 128, 129], dtype=np.int64)

array([127, 128, 129])

reshape

Both of number products should be equal to number of items present inside the array.

In [19]:
re = np.arange (1,11).reshape(2,5)
re

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
re5 = np.arange (1,21).reshape(2,5,2)
re5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [21]:
re1 = np.arange (1,11).reshape(2,5)
re2 = np.arange (1,13).reshape(3,4)
re2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

shape

gives each items consist of no.of column

In [22]:
re = np.arange(1,11).reshape(5,2)
re.shape

(5, 2)

In [23]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,7]])
arr2.shape

(1, 3)

size 
gives a number of items

In [24]:
re = np.arange(1,11).reshape(5,2)
re.size

10

itemsize

memory occupied by the items

In [25]:
re2 = np.arange(1,13).reshape(3,4)
re2.itemsize # memory occupied by the items

8

array operations:

numpy supports element-wise operations on arrays. Basic arthimetic operations like addition, sutraction, multiplication, and division are performed element-wise

In [37]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
z1 + 2 #-,*,/,**,%.

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [29]:
arrr1d = np.array([1,2,3,4,5])
re_add =arrr1d + 2
re_mul = arrr1d * 2
re_sub =arrr1d - 2
re_div = arrr1d / 2
re_add, re_mul, re_sub, re_div

(array([3, 4, 5, 6, 7]),
 array([ 2,  4,  6,  8, 10]),
 array([-1,  0,  1,  2,  3]),
 array([0.5, 1. , 1.5, 2. , 2.5]))

relational operaions

the relational opertors are also known as comparision operators, thier main function is to return either a true or false based on the value of operands

In [30]:
z2 = np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a= [11,12,11,14,15,1,17,18,9,20,21,22,23,24]
for i in a:
    if i>20:
        print(i)

21
22
23
24


In [32]:
z2[z2 >= 20]

array([20, 21, 22, 23])

In [33]:
arr1 = np.array([[-1,2,7]])
arr2 = np.array([[4,5,6]])
comp = arr1 >arr2
comp

array([[False, False,  True]])

In [34]:
ar1 = np.array([True,False,True,False])
ar2 = np.array([True,True,False,False])

_and = np.logical_and(ar1,ar2)

_or = np.logical_or(ar1,ar2)

_and , _or


#vector operations
#we can apply on both numpy array

(array([ True, False, False, False]), array([ True,  True,  True, False]))

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

addition, subtraction, multiplication,division


(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0.25, 0.4 , 0.5 ]))

In [36]:
za = np.arange(12).reshape(4,3)
zb = np.arange(12).reshape(4,3)

addition = za + zb
addition

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

arrange function

In [7]:
aa = np.arange(0,10,2)
aa1 = np.mean(aa)
aa

array([0, 2, 4, 6, 8])

In [13]:
x= np.min(aa)
x

y=np.max(aa)
y

z = np.sum(aa)
z

b = np.prod(aa)
b

c = np.median(aa)
c

d = np.std(aa)
d

e = np.var(aa)
e
print (x,e,z,b,c,d,e)


0 8.0 20 0 4.0 2.8284271247461903 8.0


In [15]:
k = np.random.random((3,3))
k

array([[0.50447923, 0.31550715, 0.93100905],
       [0.47959858, 0.43420996, 0.85423167],
       [0.42673005, 0.94317279, 0.40457314]])

In [17]:
k1 = np.round(k *100)
k1.astype('int')

array([[50, 32, 93],
       [48, 43, 85],
       [43, 94, 40]])

In [18]:
aa1 = np.sum(k1, axis=0)
aa1

array([141., 169., 218.])

In [21]:
a1 = np.max(k)

a11 = np.max(k, axis =1) # maximum of every row

a11 = np.min(k, axis =0) #minimum of every column

a2 = np.min(k)
a3 = np.sum(k)
a4 = np.prod(k) #multiplication

statistics function

In [22]:
k1 = np.random.random((3,3))

b1 = np.mean(k1)
#mean of every column
b11 = k1.mean(axis =0)

b2 = np.median(k1)

#median of every row
b22 = np.median(k1, axis=1)

b3 = np.std(k1)

b4 = np.var(k1)

b4

np.float64(0.06183122601886924)

Trignometric function

In [23]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12, 24).reshape(4,3)
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.sin(s2)


array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [25]:
np.cos(s2)


array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [27]:
np.tan(s2)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02]])

In [28]:
a = np.sin(45)
b= np.tan(45)

c=a/b
c

np.float64(0.5253219888177297)

In [29]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

In [37]:
a = np.sin(180)
b =np.cos (45)
c = np.tan(45)

sec = 1/a
cosec = 1/b
cot = 1/np.tan(45)

a,sec, cosec, cot

(np.float64(-0.8011526357338304),
 np.float64(-1.2482015977941976),
 np.float64(1.9035944074044246),
 np.float64(0.6173696237835551))

log and exponent

In [30]:
np.log(100)

np.float64(4.605170185988092)

In [31]:
np.exp(10)

np.float64(22026.465794806718)

In [33]:
np.sqrt(25)

np.float64(5.0)

In [34]:
np.power(2,3)

np.int64(8)

In [38]:
arr4 = np.array([10,20,30,40,50])
sqrt_result = np.sqrt(arr4)
print(sqrt_result)

exp_result = np.exp(arr4)

#trignometry
sin_result = np.sin(arr4)
cos_result = np.cos(arr4)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


round

The numpy.round() function rounds the elements of an array to the nearest integer or to the special number of decimals

In [39]:
#round to the nearest integer
arr = np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [40]:
#round to two decimals
arr = np.array([1.234,2.567,3.567,4.891])
rounded_arr = np.round(arr, decimals =2)
print(rounded_arr)

[1.23 2.57 3.57 4.89]


floor

The numpy.floor() function returns the largest integer less than or equal to each elements of an array.

In [42]:
arr = np.array([1.2,2.7,3.5,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [43]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[93., 14., 60.],
       [84., 68., 29.]])

ceil

The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array.

In [44]:
arr = np.array([1.2,2.7,3.5,4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [45]:
np.ceil(np.random.random((2,3))*100) # gives highest integer

array([[38., 31., 35.],
       [40., 37., 28.]])

set function

np.unionld
np.intersect1d
np.setdiff1d


In [2]:
m = np.array([1,2,3,4,5])
n= np.array ([3,4,5,6,7])



In [3]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [5]:
#set difference
np.setdiff1d(m,n)

array([1, 2])

indexing and slicing:

you can access and modify elements of arrays using indexing and slicing.indexing start 0, silicing allows you to extract portions of arrrays

In [7]:
import numpy as np

arr =np.array([10,20,30,40,50])
first_element = arr[0]
sub_array = arr[1:4]
a = arr[-1]
first_element,sub_array,a

(np.int64(10), array([20, 30, 40]), np.int64(50))

In [8]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)


In [9]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
p2[1,2]

np.int64(6)

In [63]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
p3[1,0,1]

p3[1,1,0]

np.int64(6)

In [64]:
p3[1,0,1]

np.int64(5)

In [65]:
p3[1,1,0]

np.int64(6)

In [67]:
p3[0,1,0]

np.int64(2)

In [13]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
p1[2:5]

array([2, 3, 4])

In [15]:
p1[2:5:2]

array([2, 4])

In [86]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:

p2[0:1,1:]

array([[1, 2, 3]])

In [89]:
p2[1:2, 2:]

array([[6, 7]])

In [18]:
##fetching total first row
p2[0,:]

array([0, 1, 2, 3])

In [19]:
#fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [91]:
p2[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [20]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [90]:
p2[::1,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [21]:
p3[1]

array([[4, 5],
       [6, 7]])

In [22]:
p3[0,1,:]

array([2, 3])

In [23]:
p3[1,:,1]

array([5, 7])

ISIN
we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [27]:
a = np.array([10,20,30,110])
items = [ 10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([ True,  True,  True, False])

In [28]:
a[np.isin(a,items)]

array([10, 20, 30])

In [29]:
np.isin(10, items)

array(True)

In [31]:
#create a 2d array
arr = np.array([[1,3,5],
                [8,2,4]])

#find the inex of the maximum value
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

#find the indices of maximum values along each column
max_indices_col = np.argmax(arr, axis =0)
print("indices of maximum values along each other:", max_indices_col)

Index of maximum value: 3
indices of maximum values along each other: [1 0 0]


In [32]:
import numpy as np

#create 2d array
arr = np.array([[1,3,5],
                [8,2,4]])

min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

min_indices_row = np.argmin(arr, axis =1)
print("Indices of minimum values along each row:", min_indices_row)


Index of minimum value: 0
Indices of minimum values along each row: [0 1]


array methods

np.where

the numpy.where()function return the indices of elements in an input array

In [33]:
a = np.random.randint(1,100,15)
a

array([19, 97, 84, 26, 15, 94, 40, 65, 56, 43, 53, 46, 99, 38, 52],
      dtype=int32)

In [34]:
a = np.arange(11,101)
print(a)
np.where(a>50)


[ 11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


(array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),)

In [35]:
#replace all a values> 50 with 0
np.where(a>50,0,a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0])

Itrating

In [36]:
p1 = np.arange(10)

for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [37]:
p2 = np.arange(12).reshape(3,4)

#looping on 2d array

for i in p2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [38]:
p3 = np.arange(8).reshape(2,2,2)

# looping on 2d array

for i in p3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [39]:
for i in p3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


print all items in 2d and 3d using nditer.

In [40]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [41]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


In [42]:
p4 = np.arange(12,24).reshape(3,4)
p4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
for i in np.nditer(p4):
    if i%2 ==0:
        print(i)

12
14
16
18
20
22


sorting

In [44]:
a= np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
a,b

(array([79,  2, 70, 97, 72, 23, 96, 23, 24,  5, 21, 38, 60,  3, 48],
       dtype=int32),
 array([[80, 88, 99, 39],
        [90, 77, 22, 66],
        [69, 71, 19, 30],
        [93, 62, 66, 66],
        [36, 64,  2, 34],
        [36, 30, 75, 35]], dtype=int32))

In [45]:
np.sort(a)

array([ 2,  3,  5, 21, 23, 23, 24, 38, 48, 60, 70, 72, 79, 96, 97],
      dtype=int32)

In [46]:
np.sort(a)[::-1] #descending

array([97, 96, 79, 72, 70, 60, 48, 38, 24, 23, 23, 21,  5,  3,  2],
      dtype=int32)

In [47]:
np.sort(b)

array([[39, 80, 88, 99],
       [22, 66, 77, 90],
       [19, 30, 69, 71],
       [62, 66, 66, 93],
       [ 2, 34, 36, 64],
       [30, 35, 36, 75]], dtype=int32)

In [48]:
np.sort(b, axis = 0) # column wise sorting

array([[36, 30,  2, 30],
       [36, 62, 19, 34],
       [69, 64, 22, 35],
       [80, 71, 66, 39],
       [90, 77, 75, 66],
       [93, 88, 99, 66]], dtype=int32)

append

In [49]:
np.append(b,1)

array([80, 88, 99, 39, 90, 77, 22, 66, 69, 71, 19, 30, 93, 62, 66, 66, 36,
       64,  2, 34, 36, 30, 75, 35,  1])

In [50]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [51]:
b.shape[0]

6

In [52]:
b.shape[1]

4

In [55]:
#adding one row to 2d array

np.append(b,np.ones((b.shape[0],1))).astype('int')

array([80, 88, 99, 39, 90, 77, 22, 66, 69, 71, 19, 30, 93, 62, 66, 66, 36,
       64,  2, 34, 36, 30, 75, 35,  1,  1,  1,  1,  1,  1])

In [57]:
np.append(b,np.random.random((6,1)), axis =1)

array([[80.        , 88.        , 99.        , 39.        ,  0.1533275 ],
       [90.        , 77.        , 22.        , 66.        ,  0.60752656],
       [69.        , 71.        , 19.        , 30.        ,  0.21409425],
       [93.        , 62.        , 66.        , 66.        ,  0.22134175],
       [36.        , 64.        ,  2.        , 34.        ,  0.83307797],
       [36.        , 30.        , 75.        , 35.        ,  0.14446937]])

In [56]:
#adding one row to 2d array

np.append(b,np.ones((6,1))).astype('int')

array([80, 88, 99, 39, 90, 77, 22, 66, 69, 71, 19, 30, 93, 62, 66, 66, 36,
       64,  2, 34, 36, 30, 75, 35,  1,  1,  1,  1,  1,  1])

np.unique

In [66]:
#code
e= np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

dot product
np.dot

In [59]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [60]:
c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

In [61]:
a = np.array([[11,12],[13,14]])
b = np.array([[15,16],[17,18]])
print(a)
print(b)
c = np.dot(a,b)
c

[[11 12]
 [13 14]]
[[15 16]
 [17 18]]


array([[369, 392],
       [433, 460]])

percentaile
numpy.percentile() function used to compute the nth percentile of the given data(array elements)along the specified axis

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,16)
b = np.random.randint(1,100,24).reshape(6,4)

In [3]:
np.sort(a)

array([14, 33, 36, 45, 47, 58, 59, 62, 63, 65, 65, 65, 72, 80, 87, 96],
      dtype=int32)

In [4]:
np.percentile(a,100)

np.float64(96.0)

In [5]:
np.percentile(a,50)

np.float64(62.5)

In [6]:
np.percentile(a,25)

np.float64(46.5)

In [7]:
np.percentile(a,75)

np.float64(66.75)

Flip

The numpy.flip() function revereses the order of array elements along the specified axis,preserving the shape of the array.

In [8]:
a

array([36, 65, 58, 65, 45, 96, 63, 47, 14, 87, 33, 80, 59, 72, 62, 65],
      dtype=int32)

In [9]:
np.flip(a)

array([65, 62, 72, 59, 80, 33, 87, 14, 47, 63, 96, 45, 65, 58, 65, 36],
      dtype=int32)

In [10]:
b

array([[19,  8, 30, 40],
       [23, 71, 35, 13],
       [45, 51, 32, 77],
       [ 5, 12, 42, 98],
       [93, 35, 65, 79],
       [31, 70, 78, 62]], dtype=int32)

In [11]:
np.flip(b,axis=0)

array([[31, 70, 78, 62],
       [93, 35, 65, 79],
       [ 5, 12, 42, 98],
       [45, 51, 32, 77],
       [23, 71, 35, 13],
       [19,  8, 30, 40]], dtype=int32)

In [12]:
np.flip(b,axis=1)

array([[40, 30,  8, 19],
       [13, 35, 71, 23],
       [77, 32, 51, 45],
       [98, 42, 12,  5],
       [79, 65, 35, 93],
       [62, 78, 70, 31]], dtype=int32)

Delete

the numpy.delete() function returns a new array with the deletion of sub arrays along with the mentioned axis.

In [13]:
a = np.random.randint(1,100,15)
a

array([ 4, 88, 44, 37, 65,  2, 90, 54, 90, 35, 37, 26, 67,  9, 24],
      dtype=int32)

In [14]:
np.delete(a,0)

array([88, 44, 37, 65,  2, 90, 54, 90, 35, 37, 26, 67,  9, 24],
      dtype=int32)

In [15]:
np.delete(a,[0,2,4])

array([88, 37,  2, 90, 54, 90, 35, 37, 26, 67,  9, 24], dtype=int32)

In [16]:
b

array([[19,  8, 30, 40],
       [23, 71, 35, 13],
       [45, 51, 32, 77],
       [ 5, 12, 42, 98],
       [93, 35, 65, 79],
       [31, 70, 78, 62]], dtype=int32)

In [17]:
np.delete(b,(1))

array([19, 30, 40, 23, 71, 35, 13, 45, 51, 32, 77,  5, 12, 42, 98, 93, 35,
       65, 79, 31, 70, 78, 62], dtype=int32)

Array Manipulation:

you can reshape arrays using np.reshape(), flatten them using np.flatten()0r np.ravel(),and transpose them using np.transpose()or array attriutes.

transpose ----> convert rows into columns and cloumns into rows

In [19]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [21]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
arr = np.array([[1,2,3], [4,5,6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

ravel

converting any dimension to 1d

In [23]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
p3 = np.arange(0,8).reshape(2,2,2)
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
np.ravel(p3)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
arr = np.array([[1,2,3], [4,5,6]])
flattened_arr = arr.flatten()
arr,flattened_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [30]:
p2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
p3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

inverse of array

In [33]:
#square matrix 2x2
matrix = np.array([[4,7],
                   [2,6]])

#calculate inverse
inverse_matrix = np.linalg.inv(matrix)

#original and inverse matrix
print("original matrix:")
print(matrix)

print("\ninverse matrix:")
print(inverse_matrix)

original matrix:
[[4 7]
 [2 6]]

inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


array concatention

combine arrays using functions like np.concatenate(), np.vstack(), and np.hstack().

In [34]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,4], [5,6,1]])
print(arr)
print(arr2)
concate = np.concatenate((arr,arr2),axis = 0)
concate

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 4],
       [5, 6, 1]])

stacking

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

vertical_stack =np.vstack((arr1, arr2))
horizontal_stack = np.hstack((arr1, arr2))
vertical_stack,horizontal_stack


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [36]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)
print(w1)
print(w2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [38]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

splitting:

its opposite of stacking
splitting arrays can be done with np.split(),np.vsplit(), and np.hsplit().

In [39]:
arr1 = np.array([1,2,3,4,5,6])
splitting = np.split(arr1, 2)
splitting

[array([1, 2, 3]), array([4, 5, 6])]

In [40]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [41]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [42]:
a = np.array([[1,3,6],[5,8,9],[5,5,6]])
a

array([[1, 3, 6],
       [5, 8, 9],
       [5, 5, 6]])

In [44]:
np.hsplit(a,3)

[array([[1],
        [5],
        [5]]),
 array([[3],
        [8],
        [5]]),
 array([[6],
        [9],
        [6]])]

In [45]:
np.vsplit(a,3)

[array([[1, 3, 6]]), array([[5, 8, 9]]), array([[5, 5, 6]])]

boolean indexing and fancy indexing:

it allows youu to select elements from an array based on a boolean condition.

In [46]:
arr = np.array([10,20,30,40,50])
bool_idx = arr>25
print(bool_idx)
selected_elements = arr[bool_idx]

indices = np.array([0,2,4])
fancy_selected = arr[indices]

selected_elements,fancy_selected

[False False  True  True  True]


(array([30, 40, 50]), array([10, 30, 50]))

In [48]:
g = np.random.randint(1,100,24).reshape(6,4)
g

array([[31, 37, 12, 61],
       [71, 73, 82, 44],
       [75, 24, 98, 14],
       [63, 59, 88, 48],
       [52, 98, 58, 89],
       [ 4, 17, 19, 13]], dtype=int32)

In [49]:
g >50

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [50]:
g[g>50]                        

array([61, 71, 73, 82, 75, 98, 63, 59, 88, 52, 98, 58, 89], dtype=int32)

In [51]:
g%2==0

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False, False]])

In [53]:
g[(g>50) & (g%2==0)]

array([82, 98, 88, 52, 98, 58], dtype=int32)

In [57]:
g[~(g%7==0)]

array([31, 37, 12, 61, 71, 73, 82, 44, 75, 24, 59, 88, 48, 52, 58, 89,  4,
       17, 19, 13], dtype=int32)

In [54]:
g

array([[31, 37, 12, 61],
       [71, 73, 82, 44],
       [75, 24, 98, 14],
       [63, 59, 88, 48],
       [52, 98, 58, 89],
       [ 4, 17, 19, 13]], dtype=int32)

In [56]:
g[np.array([0,3,5])]


array([[31, 37, 12, 61],
       [63, 59, 88, 48],
       [ 4, 17, 19, 13]], dtype=int32)

array broadcasting:

broadcasting allows you to perform opertaions between arrays of different shapes. 

In [58]:
scalar = 5
array = np.array([1,2,3,4,5])
result_scalar_array = scalar*array
result_scalar_array

array([ 5, 10, 15, 20, 25])

In [59]:
arr1 = np.array ([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
result_broadcasting = arr1*arr2
arr1.shape,arr2.shape,result_broadcasting


((2, 3),
 (3,),
 array([[ 10,  40,  90],
        [ 40, 100, 180]]))

file I/O WITH NUMPY

you can save and load arrays to /from files using np.save() and np.load().for instance

In [63]:
arr = np.array([[1,2,3],[4,5,6]])
np.save("my_array.npy", arr)

In [64]:
loaded_arr = np.load('my_array.npy')
loaded_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
loaded_arr[loaded_arr%2==0]

array([2, 4, 6])

Given an array [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], find the unique elements and their counts.

In [5]:
import numpy as np
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
np.unique(arr)
counts = np.unique(arr, return_counts=True)
counts


(array([1, 2, 3, 4, 5, 6, 9]), array([2, 1, 2, 1, 3, 1, 1]))

Create a diagonal matrix with the elements [2, 4, 6] on the diagonal.

In [6]:
diagonal_matrix = np.diag([2, 4, 6])
diagonal_matrix

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

Given a 2D array, swap the first and second rows.

In [10]:
arr1 = np.arange(8).reshape(2,4)
print(arr1)
np.transpose(arr1)

[[0 1 2 3]
 [4 5 6 7]]


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Find the index of the maximum value in the array [8, 3, 7, 1, 2, 6, 5].

In [11]:
arr2 = np.array([8, 3, 7, 1, 2, 6, 5])
np.max(arr2)

np.int64(8)

Given a 1D array, find the indices where the values are even.

In [35]:
arr3 = np.array([0,1,2,3,4,5,6])
np.where(arr3%2==0)


(array([0, 2, 4, 6]),)

Create a 5x5 matrix with 1 on the border and 0 inside.

In [53]:
arr4 = np.ones((5,5), dtype='int')
arr4[1:-1, 1:-1]=0
arr4


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Given two arrays [1, 2, 3] and [4, 5, 6], perform element-wise multiplication.

In [54]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
multiplication = ar1 *ar2
multiplication

array([ 4, 10, 18])

Count the number of elements greater than 3 in the array [1, 4, 2, 7, 5, 0].

In [55]:
arr7 = np.array([1, 4, 2, 7, 5, 0])
count = np.sum(arr7 > 3)
count


np.int64(3)

Reshape the array [1, 2, 3, 4] into a 2x2 matrix.

In [60]:
ar7 = np.array([1, 2, 3, 4])
matrix = ar7.reshape(2,2)
matrix

array([[1, 2],
       [3, 4]])

Given two matrices A and B, check if they are element-wise equal. A = [[1, 2], [3, 4]] B = [[1, 2], [3, 4]]


In [61]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
equal = np.all(a==b)
equal


np.True_

Calculate the mean along each row of a 2D array. [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [68]:
rows = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.mean(rows, axis=1)

array([2., 5., 8.])

Replace all odd numbers in the array [10, 15, 20, 25, 30] with -1.

In [69]:
arr = np.array([10, 15, 20, 25, 30])
arr[arr % 2 != 0] = -1
print(arr)

[10 -1 20 -1 30]
